version: "3.10"
networks:
  app-tier:
    driver: bridge
services:
  fastapi:
    build: ./fastapi
    expose:
      - "5000"
    ports:
      - "5000:5000"
    environment:
      - QDRANT_HOST=qdrant
    depends_on:
      - qdrant
    networks:
      - app-tier
    volumes:
      - ./fastapi:/app:Z
  sveltekit:
    build: ./sveltekit
    ports:
      - 3000:3000
    networks:
      - app-tier
    depends_on:
      - fastapi
    volumes:
      - ./sveltekit:/app:Z
    environment:
      - VITE_BACKEND_URL=http://localhost:5000
  qdrant:
    build: ./qdrant
    ports:
      - 6333:6333
    volumes:
      - ./data/qdrant_storage:/qdrant/storage

    networks:
      - app-tier

volumes:
  app-qdrant-data: